language: node_js
node_js:
  - 10.16.3

before_install: cd application

services:
  - postgresql

before_script:
  - psql -c 'create database rolebasedauth_test' -U postgres
  - npm i -g sequelize-cli
  - sequelize db:migrate
  - sequelize db:seed:all
